name: Docker container

on:
  push:
    branches: none # [ "master" ]
  pull_request:
    branches: none # [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lorisleiva/laravel-docker:7.4
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Generate key
        run: php artisan key:generate

      - name: Migrate seed
        run: |
          php artisan migrate --force
          php artisan db:seed --class=TestSeeder

      - name: Run Testsuite
        run: php artisan test
