name: Tests

on:
  push:
    branches:
      - master
      - develop
      - '*.x'
  pull_request:
    branches:
      - master
      - develop
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  phpunit:
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ 'kirschbaumdevelopment/laravel-test-runner:8.1','kirschbaumdevelopment/laravel-test-runner:8.2']
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.php-versions }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Migrate seed
        run: |
          php artisan migrate --force
          php artisan db:seed --class=TestSeeder

      - name: Run Testsuite
        run: php artisan test
